const externalElements = {
  // drd
  'View DRD': '返回图形界面',
  'Definition name': '决策定义名称',
  'Definition ID': '决策定义ID',
  'Open decision table': '打开决策',
  'Change type': '修改类型',
  'Connect to other element': '连接到其他元素',
  'Append decision': '追加决策',
  'Append business knowledge model': '追加业务知识模型',
  'Append knowledge source': '追加知识来源',
  'Append input data': '追加输入数据',
  'Add text annotation': '添加文本注解',
  Delete: '删除',
  'Literal expression': 'Literal 表达式',
  'Literal Expression': 'Literal 表达式',
  'Decision table': '设置决策表',
  Empty: '置空',
  'Activate hand tool': '激活手型工具',
  'Activate lasso tool': '激活套索工具',
  'Create decision': '创建决策',
  'Create input data': '创建输入数据',
  'Create knowledge source': '创建知识来源',
  'Create knowledge model': '创建业务知识模型',

  // decision table
  Unique: '唯一',
  First: '第一个',
  Priority: '优先级',
  Collect: '采集',
  Any: '任意',
  'Collect (Sum)': '采集 (求和)',
  'Collect (Min)': '采集 (最小)',
  'Collect (Max)': '采集 (最大)',
  'Collect (Count)': '采集 (总数)',
  'Rule order': '规则排序',
  'Output order': '输出排序',

  'Hit policy:': '命中策略：',
  'Decision name': '决策名称',
  Annotations: '备注',

  When: '输入',
  Input: '输入',
  Then: '输出',
  Output: '输出',
  And: '和',
  'Add input': '添加输入',
  'Move input': '移动输入',
  'Add output': '添加输出',
  'Move output': '移动输出',
  'Add rule': '添加规则',
  'Move rule': '移动规则',

  Expression: '输入变量名',
  'Output name': '输出变量名',
  Type: '数据类型',
  'Input type': '输入数据类型',
  'Output type': '输出数据类型',
  'Predefined values': '预定义值',
  'Clear predefined values': '清除预定义值',
  'No values': '没有值',
  'Add predefined values': '添加预定义值',

  value: '值',
  string: '字符串 (string)',
  boolean: '布尔值 (boolean)',
  number: '数字 (number)',
  double: '浮点数 (double)',
  long: '长整数 (long)',
  integer: '整数 (integer)',
  collection: '集合 (collection)',
  date: '日期 (date)',
  time: '时间 (time)',
  dateTime: '日期+时间 (dateTime)',
  dayTimeDuration: '持续时间 (日期+时间) (dayTimeDuration)',
  yearMonthDuration: '持续时间 (年月) (yearMonthDuration)',

  Edit: '编辑',
  'Edit number': '编辑值',
  'Edit string': '编辑字符串',
  'Edit boolean': '编辑布尔值',
  'Edit date': '编辑日期',
  'Edit time': '编辑时间',
  'Edit date time': '编辑日期时间',
  'Edit duration': '编辑持续',
  'Edit date and time': '编辑日期时间',

  Equals: '等于',
  Less: '小于',
  'Less or equals': '小于等于',
  Greater: '大于',
  'Greater or equals': '大于等于',
  'Match one': '匹配一个',
  'Match none': '不匹配',

  'Start value': '起始值',
  'End value': '结束值',
  'Set time': '设置时间',
  'Set date': '设置日期',
  'Set value': '设置值',
  'Set date and time': '设置日期时间',
  'Set duration': '设置持续',
  'Use today': '使用今天',
  'Use now': '使用此刻',
  Include: '包含',
  Exclude: '不包含',
  Range: '范围',
  Comparison: '比较',
  Yes: '是',
  No: '否',

  // 策略说明
  'No overlap is possible and all rules are disjoint. Only a single rule can be matched': '',
  'Rules may overlap. The first matching rule will be chosen':
    '规则可能会重复。将选择第一个匹配规则',
  'Rules may overlap. The one with the highest priority will be chosen':
    '规则可能会重复。将选择具有最高优先级的匹配规则',
  'Rules may overlap. Their output have to match': '规则可能会重复。它们的输出可以任意匹配',
  'Collects the values of all matching rules': '收集所有匹配规则的值',
  'Collects the values of all matching rules and sums up to a single value':
    '收集所有匹配规则的值，并求和为一个值',
  'Collects the values of all matching rules and uses the lowest value':
    '收集所有匹配规则的值，并使用最小值',
  'Collects the values of all matching rules and uses the highest value':
    '收集所有匹配规则的值，并使用最大值',
  'Collects the values of all matching rules and counts the number of them':
    '收集所有匹配规则的值并计算它们的数量',
  'Collects the values of all matching rules in rule order': '按规则顺序收集所有匹配规则的值',
  'Collects the values of all matching rules in decreasing output priority order':
    '按输出优先级降序收集所有匹配规则的值',

  'Copy output column': '拷贝输出列',
  'Cut output column': '剪切输出列',
  'Paste output column left': '向左粘贴输出列',
  'Paste output column right': '向右粘贴输出列',
  'Add output column left': '向左添加输出列',
  'Add output column right': '向右添加输出列',
  'Remove output column': '移除输出列',

  'Copy input column': '拷贝输入列',
  'Cut input column': '剪切输入列',
  'Paste input column left': '向左粘贴输入列',
  'Paste input column right': '向右粘贴输入列',
  'Add input column left': '向左添加输入列',
  'Add input column right': '向右添加输入列',
  'Remove input column': '移除输入列',

  'Copy rule': '复制规则',
  'Cut rule': '剪切规则',
  'Paste rule above': '将规则粘贴到上面',
  'Paste rule below': '将规则粘贴到下面',
  'Add rule above': '上方插规则',
  'Add rule below': '在下面添加规则',
  'Remove rule': '移除规则',
  'Add cell description': '添加单元格描述',

  'Date must match pattern yyyy-MM-dd': '日期必须符合 yyyy-MM-dd 格式',
  'Time must match pattern hh:mm:ss[time zone]': '时间必须符合 hh:mm:ss[time zone] 格式',
  'Date and time must match pattern yyyy-MM-ddTHH:mm:ss[time zone]':
    '日期时间必须符合 yyyy-MM-ddTHH:mm:ss[time zone] 格式',
  'Must match PnDTnH': '持续时间必须符合 PnDTnH 格式',
  'Must match PnYnM': '持续时间必须符合 PnYnM 格式',

  'Function signature': '函数签名',

  // Literal Expression
  'Edit function kind': '编辑函数类型',
  'Edit formal parameters': '编辑形式参数(形参)',
  Name: '名称',
  'Add parameter': '添加参数',
  Result: '返回结果',
  'Variable name': '变量名称',
  'Result type': '返回类型',

  // panel
  decisionService: '决策服务',
  encapsulatedDecision: '',
  outputDecision: '',
};

export default externalElements;
